title: Sue's Data Analysis Projects
author: suekim1210
email: suekim1210@gmail.com
description: I will update my data analysis on some datasets
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
